name: CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Biome (lint + format check)
        run: pnpm run check

      - name: Typecheck
        run: pnpm -r --filter ./packages/** run typecheck

      - name: Build
        run: pnpm -r --filter ./packages/** run build

      - name: Test
        run: pnpm -r --filter ./packages/** run test

      - name: Ensure origin/main exists (PR)
        if: github.event_name == 'pull_request'
        run: git fetch origin main:refs/remotes/origin/main --depth=1

      - name: Check for changeset (only on PR)
        if: github.event_name == 'pull_request'
        run: |
          # Skip changeset check on release branches
          if [[ "${{ github.head_ref }}" == "changeset-release/main" || "${{ github.head_ref }}" == release/* ]]; then
            echo "⏭️ Skipping changeset check for release PR/branch (${{ github.head_ref }})"
            exit 0
          fi

          if ! pnpm changeset status --since=origin/main; then
            echo "❌ No changeset found. Please run 'pnpm changeset' to add a changeset for your changes."
            echo "If this PR doesn't require a release (e.g., docs, CI changes), add an empty changeset:"
            echo "pnpm changeset --empty"
            exit 1
          else
            echo "✅ Changeset found!"
          fi
